[package]
name = "quick-startup-folder"
version = "0.3.1"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
dont_disappear = "3.0.1"
libc = "0.2.164"
opener = "0.7.2"
winapi = { version = "0.3.9", features = [
    "winuser",
    "handleapi",
    "processthreadsapi",
    "securitybaseapi",
] }
