name: Build and Release for Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build the project for Windows
      run: |
        cargo build --release --target x86_64-pc-windows-msvc

    - name: Create release on GitHub
      id: create_release
      run: |
        REPO="ingobeans/quick-startup-folder"
        API_URL="https://api.github.com/repos/$REPO/releases"
        RESPONSE=$(curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"tag_name": "latest","name": "latest","body": "Latest release","draft": false,"prerelease": false}' \
          $API_URL)
        echo "Release created with ID: $(echo $RESPONSE | jq -r '.id')"

    - name: Upload EXE to GitHub Release
      run: |
        EXE_PATH="./target/x86_64-pc-windows-msvc/release/quick-startup-folder.exe"
        RELEASE_ID=$(echo "${{ steps.create_release.outputs.response }}" | jq -r '.id')
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @"$EXE_PATH" \
          "https://uploads.github.com/repos/$REPO/releases/$RELEASE_ID/assets?name=quick-startup-folder.exe"
